[tool.poetry]
name = "xnemogcm"
version = "0.3.4"
description = "Interface to open NEMO global circulation model output dataset and create a xgcm grid."
license = "MIT"
homepage = "https://github.com/rcaneill/xnemogcm"
authors = ["Romain Caneill <romain.caneill@gu.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
dask = {extras = ["array"], version = "*"}
f90nml = {optional = true, version = ">=1.3.1"}
netcdf4 = ">=1.5.8"
xarray = ">=0.21.1"
xgcm = {optional = true, version = ">=0.6.0"}

[tool.poetry.extras]
namelist = ["f90nml"]
metrics = ["xgcm"]

[tool.poetry.dev-dependencies]
jupyterlab = ">=3.2.8"
line-profiler = "*"
matplotlib = ">=3.5.1"
memory-profiler = "*"
py-heat-magic = "*"
twine = ">=3.8.0"
xgcm = ">=0.6.0"
pytest = ">=6.2.5"
